### PR TITLE
Make Momento stackable and update recipe

### PR DESCRIPTION
**Pull request by cpaca**

### CODE REVIEW

**Comment by dlee13** [comment]
I was going cross-eyed looking at Klin's code trying to understand if this would interfere with onion ring

**Comment by cpaca** [comment]
It wouldn't, due to the last commit I put in

**Comment by cpaca** [comment]
Correction: It never would have, since PlayerInventory.getContents() doesn't (to my knowledge) return the offhand

**Comment by dlee13** [comment]
From checking the javadocs, PlayerInventory inherits getContents from Inventory, and that does return every slot

**Comment by cpaca** [comment]
From what I can tell (both googling and checking docs) it doesn't return getArmorContents?

**Comment by cpaca** [comment]
It also doesn't return getExtraContents but I can't figure out what's in extraContents

**Comment by dlee13** [comment]
Indexes 36 through 39 are the armor slots. Index 40 is the offhand slot. And getContents returns the entire ItemStack array. That includes what getExtraContents would return. For a player, getExtraContents would probably be the crafting slots and crafting result slot. Those are probably after index 40.

**Comment by cpaca** [comment]
Interesting!

Either way, with the last commit I pushed, it doesn't matter since onion ring only deletes your weapon (and itself) if keepInventory is off

**Pull request merged**
